### ISSUE TITLE
nearestlocation method fails when AbstractSpatialData has Integer coordinates

### ISSUE THREAD

**Issue by sdyinzhen** [juliohm/GeoStats.jl#18] opened 2018-04-11 04:27 UTC
Julia Version 0.6.2
GeoStats 0.5.5

The **EstimationProblem(geodata, domain, :poro)**  does not work if the geodata's coordinates and domain data's coordinates do have the same data type.

**Comment by juliohm** [comment] 2018-04-11 04:28
Hi David, I think the issue you pointed out to me internally is related to the fact that your case had integer coordinates. I will rename the title of the issue and address it later when I find some time. Thanks for reporting it.

**Comment by juliohm** [comment] 2018-04-11 04:43
Actually you are right, this is a problem caused by the fact that both objects data and domain must have the same coordinate type by design. In that case, I will just add an assertion in the `EstimationProblem` class to make sure that this is the case and to elucidate future users. :+1:

**Comment by juliohm** [comment] 2018-04-11 04:58
Fixed in https://github.com/juliohm/GeoStatsBase.jl/commit/9996ad9f5291198d391f2c074df884524de440f2

**Closed by juliohm** 2018-04-11 04:58 UTC
Labels: enhancement
