### ISSUE TITLE
InexactError: Int64

### ISSUE THREAD

**Issue by syncharny** [juliohm/GeoStats.jl#38] opened 2019-06-06 13:01 UTC
Any idea what's going on here - it seems like something about the grid is causing this error. 

![Screen Shot 2019-06-06 at 6 56 47 AM](https://user-images.githubusercontent.com/22597574/59034541-74bb1d80-8828-11e9-832d-3ffe1bb3ae65.png)

```
mi2m = 1609.
grid_spacing = 1*mi2m
grid_domain = RegularGrid((x_extent, y_extent), (ceil(min_x), ceil(min_y)),
              (1., 1.))
```
I was doing a mile spacing, but nothing works

Here's the full error:

> InexactError: Int64(0.23931789643928889) Type at float.jl:703 [inlined] convert at number.jl:7 [inlined] setindex!(::Array{Int64,1}, ::Float64, ::Int64) at array.jl:767 solve_globally(::EstimationProblem{GeoDataFrame{Float64,2,DataFrame},RegularGrid{Float64,2},SimpleMapper}, ::Symbol, ::Dict{Symbol,NamedTuple}) at kriging.jl:252 solve(::EstimationProblem{GeoDataFrame{Float64,2,DataFrame},RegularGrid{Float64,2},SimpleMapper}, ::Kriging) at kriging.jl:151 top-level scope at none:0

**Comment by juliohm** [comment] 2019-06-06 13:09
I'm far from my laptop at the moment, but the issue seems to be related to
the types of the arguments to the RegularGrid constructor. Can you please
double check the types of the variables in the code?

You can find the documentation of RegularGrid in Juno.

**Comment by syncharny** [comment] 2019-06-06 13:16
Thanks for the quick response. I am actually converting the dimensions to an int because I couldn't get it to function with all floats:

x_extent = ceil(Int,max_x - min_x)
y_extent = ceil(Int,max_y - min_y)

So the types are int, float, float. I think that jive with the examples in the docs.

**Comment by juliohm** [comment] 2019-06-06 13:25
Yes it should work. And the error occurs at the RegularGrid line or later?
Make sure the type of the coordinates is the same both in the grid and in
the geodf. I'll try to take a look later tonight if you share a minimum
code reproducing the error.

**Comment by syncharny** [comment] 2019-06-06 14:36
It happens when I try to solve. I'll share some code this afternoon - I wouldn't be surprised if this was a juliet issue and not a geostats issue

**Comment by juliohm** [comment] 2019-06-06 15:07
Thanks. If you share some code it will help solving the issue.

**Comment by juliohm** [comment] 2019-06-12 01:48
I am closing this issue assuming you have solved it.

**Closed by juliohm** 2019-06-12 01:48 UTC
Labels: invalid
