### ISSUE TITLE
Unikrig(...) | Undesired behavior in different float precisions

### ISSUE THREAD

**Issue by masiddique** [juliohm/GeoStats.jl#6] opened 2017-03-12 00:07 UTC
Hi,

Sorry I'm here to bother you again. I'm noticing some anomalous, or say, undesired behavior of the `unikrig()` function when changing the float precision for the inputs. I first noticed it when working with my project data; unfortunately I cannot share it with you due to restrictions from the data provider. However, I managed to recreate the situation by slightly modifying the example code you've put in the "Documentation" section.

```
# create some data
import Distributions: Gamma
srand(0);rand(Gamma(2.0))
dim, nobs = 3, 1000
X1 = rand(dim, nobs); z = rand(nobs)
X2 = convert(Matrix{Float32},X1)
X3 = convert(Matrix{Float64},X2)

# target location
x₀ = rand(dim)

# define a covariance model
cov = GaussianCovariance(1.,1.) # sill and range

# estimation
μ1, σ² = unikrig(x₀, X1, z, cov=cov)
μ2, σ² = unikrig(x₀, X2, z, cov=cov)
μ3, σ² = unikrig(x₀, X3, z, cov=cov)

(μ1, μ2, μ3)
```
`(2.198385878270528,1.843946672568211,-2.185270204569795)`

Note that each of the three predicted values are different.

Regarding μ1 and μ2: 
X1 is of type Matrix{Float64}. Truncating the precision to Float32 for X2 implies X1 != X2, and therefore,  we can expect that μ1 != μ2. However, the user should generally be aware of such a possibility. 

Regarding μ2 and μ3: 
The difference between these two is problematic. Increasing the precision of an existing float from 32 to 64 bits doesn't change the value (X3 should be equal to X2, except for additional 0's at the far decimal places). Therefore, the difference between μ2 and μ3 seems like a bug! 

I did some preliminary troubleshooting. I think this problem has to do with the following statement (and probably others similar to it): 

`g = Float64[γ(norm(X[:,j]-x₀)) for j=1:n]` # line 100 (kriging.jl)

The code `γ(norm(X[:,j]-x₀)) for j=1:n` may not yield the same values when `X` is float32 or float64. Please look into this issue when you've some time. Thanks.

**Comment by juliohm** [comment] 2017-03-12 04:03
Hi @masiddique, this is definitely a bug, thank you very much for catching it. I will spend some time looking into it, please let me know if you have a fix in mind.

**Comment by masiddique** [comment] 2017-03-12 09:49
I have poured in some effort. The most I've figured as yet is the fact that the condition number (CN) of the matrix `Γ` (in `unikriging()`) is coming out very large (on the order of > 10) which explains the sensitivity to floating points truncation. I think we should add a flag to see whether the CN is greater than a PRESET_THRES anyway, so the user is warned; however, for an example as simple as above, it's difficult to live with it!

**Comment by juliohm** [comment] 2017-03-12 18:03
That is a very good point, also notice that the problem of Float32 vs. Float64 is manifested in all Kriging variants: simple, ordinary and universal.

For simple and ordinary Kriging the system should be better behaved given that the covariance C is used directly instead of the variogram Γ. However, by increasing the number of observations from 100 to 1000 I get the same inconsistency that you raised about the `unikrig` results.

**Comment by juliohm** [comment] 2017-03-12 21:16
Meanwhile, if you are calling the estimators inside of a loop like in a sequential simulation, you can try to restrict the neighborhood of observations and check if the error is alleviated.

I rewrote the estimators so that you can use them in a loop without building the Kriging system every time a new location is targeted. The API changed a little, you can check an example in the README.

I will continue debugging the Float32 vs. Float64 issue, see if we can do something about it.

**Comment by masiddique** [comment] 2017-03-13 08:31
That's great. I'll check these out. Thanks

**Comment by juliohm** [comment] 2017-03-14 01:33
Added more tests for the Kriging estimators, all of them are passing: https://github.com/juliohm/GeoStats.jl/blob/master/test/runtests.jl

If you have other tests in mind that could rule out possibilities, please let me know.

**Comment by juliohm** [comment] 2017-05-05 20:53
I finally had a break to look into this again. The issue is now fixed in the master branch and I will tag a new release soon. It had to do with the linear solver triggered by Julia. I am now forcing a factorization explicitly (either Cholesky or LU depending on the Kriging variant).

**Closed by juliohm** 2017-05-05 20:53 UTC
